[package]
name = "single_relation"
version = "0.1"
lean_version = "leanprover-community/lean:3.24.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "bc94d05242714263947fa485f3b64b911bb84faf"}
